on:
  pull_request:

name: "Trigger: Push action"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
